// src/App.vue
<script setup lang="ts">
import Navbar from './components/landing/Navbar.vue'
import Hero from './components/landing/Hero.vue'
import FeatureGrid from './components/landing/FeatureGrid.vue'
import Testimonials from './components/landing/Testimonials.vue'
import Pricing from './components/landing/Pricing.vue'
import CTA from './components/landing/CTA.vue'
import Footer from './components/landing/Footer.vue'
</script>

<template>
  <main class="min-h-screen">
    <Navbar />
    <Hero />
    <FeatureGrid />
    <Testimonials />
    <Pricing />
    <CTA />
    <Footer />
  </main>
</template>

// app/page.tsx
import { Header } from "@/components/header"
import { HeroSection } from "@/components/hero-section"
import { FeaturesSection } from "@/components/features-section"
import { TestimonialsSection } from "@/components/testimonials-section"
import { PricingSection } from "@/components/pricing-section"
import { CTASection } from "@/components/cta-section"
import { Footer } from "@/components/footer"

export default function Home() {
  return (
    <main className="min-h-screen">
      <Header />
      <HeroSection />
      <FeaturesSection />
      <TestimonialsSection />
      <PricingSection />
      <CTASection />
      <Footer />
    </main>
  )
}
